# Generated by Django 3.2.7 on 2021-10-21 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('profile_image', models.ImageField(upload_to='')),
                ('second_image', models.ImageField(upload_to='')),
                ('third_image', models.ImageField(upload_to='')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('avg', models.DecimalField(max_digits=2, decimal_places=1, default=0)),
                ('nr_com', models.DecimalField(max_digits=4, decimal_places=1, default=0)),
                ('total_likes', models.IntegerField(default=0))

            ],
        ),
    ]
