# Generated by Django 3.2.7 on 2021-11-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_movies', '0007_auto_20211126_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='avg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='list_movies.product'),
        ),
    ]
