# Generated by Django 3.2.7 on 2021-11-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_movies', '0008_auto_20211126_1526'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='product',
            name='total_likes',
        ),
    ]
